model: 'detectionANDkeypoints' #prn or detectionANDkeypoints
backbone: 'mobilenetv2'
output_path: '/home/vietnguyen/refactor/demo/convert/onnx/mobilenetv2_detectANDkps.onnx'
checkpoint: '/home/vietnguyen/refactor/demo/models/mobilenetv2_prn_subnet/ckpt_1_0.00280.h5.best'