COMMON:
  GPUS: [0]
DATASET:
  data_dir: '/mnt/hdd10tb/Datasets/COCO2017/images'
  mask_dir: '/mnt/hdd10tb/Datasets/COCO2017/viet_data/'
  json_path: '/home/vietnguyen/MultiPoseNet/COCO.json'
  coco_root: '/mnt/hdd10tb/Datasets/COCO2017'
MODEL:
  inp_size: 480
  feat_stride: 4
  backbone: 'resnet50'
VAL:
  ckpt: '/home/vietnguyen/MultiPoseNet/extra/models/res50_detection_subnet/final_ckpt.h5'
  output_path: '/home/vietnguyen/refactor/demo/output/output.avi'
  video_path: '/home/vietnguyen/MultiPoseNet/son1.avi'
  json_result_path: '/home/vietnguyen/refactor/demo/output/multipose_coco2017_results.json'
  dataset_type: 'test'