COMMON:
  GPUS: [0, 1, 2]
  saved_dir: '/home/vietnguyen/MultiPoseNet/extra/models/resnet50_detection_subnet/'
DATASET:
  data_dir: '/mnt/hdd10tb/Datasets/COCO2017/images'
  mask_dir: '/mnt/hdd10tb/Datasets/COCO2017/viet_data/'
  json_path: '/home/vietnguyen/MultiPoseNet/COCO.json'
FROZEN_WEIGHTS_LIST:
#  backbone: ['conv1', 'bn1', 'layer1', 'layer2', 'layer3', 'layer4', 'layer5', 'layer6', 'layer7', 'layers',
#             'my_conv1', 'my_conv2', 'my_conv3', 'my_conv4']
  backbone: ['backbone']
  detection:
      backbone: ['conv6', 'conv7', 'latlayer1', 'latlayer2', 'latlayer3', 'toplayer0', 'toplayer1', 'toplayer2']
      detection: ['regressionModel', 'classificationModel']
  keypoints:
      backbone: ['toplayer', 'flatlayer1', 'flatlayer2', 'flatlayer3', 'smooth1', 'smooth2', 'smooth3']
      keypoints: ['convt1', 'convt2', 'convt3', 'convt4', 'convs1', 'convs2', 'convs3', 'convs4', 'upsample1',
                  'upsample2', 'upsample3', 'conv2', 'convfin', 'convfin_k2', 'convfin_k3', 'convfin_k4', 'convfin_k5']
  prn: ['prn']

FROZEN_MODULES: ['prn', 'detection']

MODEL:
  subnet: 'keypoints'
  backbone: 'mobilenetv2'
  inp_size: 480 #kp + prn - 480, detection - 608
  feat_stride: 4

TRAIN:
  num_epochs: 2
  batch_size: 8
  optimizer: 'adam'
  weight_decay: 0.000
  init_lr: 0.0001
  lr_decay: 0.1

  ckpt: '/home/vietnguyen/MultiPoseNet/extra/models/res50_detection_subnet/final_ckpt.h5'
  re_init: false
  ignore_opt_state: false

  val_nbatch_end_epoch: 2000

  print_freq: 50
  use_tensorboard: false

  num_of_keypoints: 3 #minimum number of keypoints for training PRN
