COMMON:
  GPUS: [0] #only run in one gpu if you want to get accuracy measure
DATASET:
  data_dir: '/mnt/hdd10tb/Datasets/COCO2017/images'
  mask_dir: '/mnt/hdd10tb/Datasets/COCO2017/viet_data/'
  json_path: '/home/vietnguyen/MultiPoseNet/COCO.json'
  coco_root: '/mnt/hdd10tb/Datasets/COCO2017'
MODEL:
  subnet: 'keypoints'
  backbone: 'resnet50'
  inp_size: 480 #kp + prn - 480, detection - 608
  feat_stride: 4

VAL:
  ckpt: '/home/vietnguyen/MultiPoseNet/extra/models/res50_detection_subnet/final_ckpt.h5'
  measure: 'accuracy' #accuracy or loss
  batch_size: 25
  num_of_keypoints: 3
  dataset_type: 'val' #test