COMMON:
  GPUS: [1] #only run in one gpu if you want to get accuracy measure
DATASET:
  data_dir: '/mnt/hdd10tb/Datasets/COCO2017/images'
  mask_dir: '/mnt/hdd10tb/Datasets/COCO2017/viet_data/'
  json_path: '/home/vietnguyen/MultiPoseNet/COCO.json'
  coco_root: '/mnt/hdd10tb/Datasets/COCO2017'
MODEL:
  subnet: 'keypoints'
  backbone: 'resnet101'
  inp_size: 480 #kp + prn - 480, detection - 608
  feat_stride: 4

VAL:
  ckpt: '/home/vietnguyen/refactor/demo/models/ckpt_baseline_resnet101.h5'
  output_path: '/home/vietnguyen/refactor/demo/output/output.avi'
  video_path: '/home/vietnguyen/MultiPoseNet/son1.avi'
  json_result_path: '/home/vietnguyen/refactor/demo/output/multipose_coco2017_results.json'
  measure: 'accuracy' #accuracy
  batch_size: 25
  num_of_keypoints: 3